### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#166]
- [x] Basic support
  - [x] Permitted contents
  - [x] Attributes
  - [x] namespaceURI (jsx/vue/svelte/pug/astro)
- [x] SVG Specific rules
  - [x] `svg-no-multiple-title` #296
  - [x] ~~`svg-title-must-be-first-child`~~ #296
  - [x] ~~`svg-disallow-unknown`~~ #295
  - [x] ~~`svg-disallow-embedded-html`~~ #294
  - [x] ~~`svg-filter-reference-relationship`~~ #293
  - [x] ~~`svg-no-use-text-element` (The purpose is to convert text to paths. Must note about accessibility.)~~ #292
  - [x] ~~`svg-no-use-xmlns-attr-in-html`~~ #291
- [x] ~~Browser Compatibility~~ #271
- [x] JSX Attribute support for SVG #299

**Comment by JounQin** [comment]
Is there any plan to support this feature?

I'm currently suffering due to rule `case-sensitive-tag-name`:

```html
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient></linearGradient>
  </defs>
</svg>

<!-- and also -->
<svg xmlns="http://www.w3.org/2000/svg">
  <svg:defs>
    <svg:linearGradient></svg:linearGradient>
  </svg:defs>
</svg>
```

**Comment by YusukeHirao** [comment]
@JounQin 

It is may a bug.


It ignores foreign elements.

https://github.com/markuplint/markuplint/blob/d993bcbf7d43c95e155afbb91be57f958451b1cc/packages/%40markuplint/rules/src/case-sensitive-tag-name/index.ts#L14-L16

It was may wrong to detect whether a foreign element.
And some languages except HTML cannot detect that yet.

---

The solution temporarily is to use `childNodeRules`:

```json
{
    "childNodeRules": [
        {
            "selector": "svg",
            "inheritance": true,
            "rules": {
                "case-sensitive-tag-name": true
            }
        }
    ]
}
```

**Comment by JounQin** [comment]
I'm using my own `markuplint-angular-parser`, so maybe I should add `isForeignElement` property correctly.

What does `isForeignElement` mean?

**Comment by JounQin** [comment]
OK, I understand now.

https://github.com/markuplint/markuplint/blob/15a0b247a0fff71f2f65121afb5f8e01e59b2ddb/packages/%40markuplint/ml-core/src/ml-dom/tokens/omitted-element.ts#L23

For the following

```html
<svg:defs>
  <svg:linearGradient></svg:linearGradient>
</svg:defs>
```

I also need to set the namespace correctly as `http://www.w3.org/2000/svg` because it's in `svg` namespace.
